FROM nginx:1.27-alpine

COPY deploy/client-package/nginx.conf /etc/nginx/conf.d/default.conf
COPY deploy/client-package/40-generate-env-config.sh /docker-entrypoint.d/40-generate-env-config.sh
RUN chmod +x /docker-entrypoint.d/40-generate-env-config.sh

COPY frontend/dist-client-package/ /usr/share/nginx/html/
