"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-t@l0+4bomqjrs1798fw_jr_6p=#@zh!^m1*3y)c8=gzdyu^-*n')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = [h.strip() for h in config('ALLOWED_HOSTS', default='').split(',') if h.strip()]

# Derrière un reverse proxy Nginx (prod) : Nginx termine le TLS et parle en
# clair à Daphne en interne, donc Django ne voit jamais directement
# `https://` sans ces deux réglages — nécessaire pour que Django admin
# (CSRF, cookies sécurisés) fonctionne correctement une fois exposé via un
# vrai domaine. Inertes en dev (`ALLOWED_HOSTS` vide → liste vide, Nginx
# absent → header jamais envoyé).
CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in ALLOWED_HOSTS]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# --- Licence (§licence) ---
# `EST_SERVEUR_MAITRE=True` UNIQUEMENT sur l'installation qui héberge les
# abonnements de tous les clients (le VPS, à terme sur son propre domaine) —
# cette installation ne pointe jamais vers elle-même et n'applique jamais les
# restrictions. Toute installation cliente laisse `EST_SERVEUR_MAITRE` à
# `False` et renseigne les trois autres réglages pour se signaler
# périodiquement (`manage.py verifier_licence`, cf. README).
EST_SERVEUR_MAITRE = config('EST_SERVEUR_MAITRE', default=False, cast=bool)
LICENCE_MASTER_URL = config('LICENCE_MASTER_URL', default='').rstrip('/')
LICENCE_IDENTIFIANT = config('LICENCE_IDENTIFIANT', default='')
LICENCE_CLE_API = config('LICENCE_CLE_API', default='')


# Application definition

INSTALLED_APPS = [
    # `daphne` doit être le tout premier app : c'est ce qui fait que
    # `manage.py runserver` sert l'application ASGI (HTTP + WebSocket, cf.
    # config/asgi.py) au lieu du serveur WSGI par défaut de Django, qui
    # ignore silencieusement toute route WebSocket (404 sur `/ws/...`).
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Tiers
    'rest_framework',
    'corsheaders',
    'channels',
    # App locale
    'kds_core',
]

AUTH_USER_MODEL = 'kds_core.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # doit être placé avant CommonMiddleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'kds_core.middleware.CurrentUserMiddleware',
    'kds_core.middleware.LicenceEnforcementMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

if config('USE_SQLITE', default=False, cast=bool):
    # TEMPORAIRE : le socle attend Postgres (voir README). Repasser sur
    # Postgres dès que `docker compose up -d` fonctionne (retirer USE_SQLITE
    # du .env).
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='kds_db'),
            'USER': config('DB_USER', default='kds_user'),
            'PASSWORD': config('DB_PASSWORD', default='changeme'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5433'),  # 5432 pris par un Postgres natif sur ce poste
        }
    }

# --- Django REST Framework ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# --- CORS (à restreindre en production aux domaines des tenants) ---
# Dev par défaut (rien dans .env) : ouvert à tout, comme avant. Dès que
# CORS_ALLOWED_ORIGINS est renseigné en prod (liste séparée par des
# virgules), on bascule sur une liste blanche stricte plutôt que
# CORS_ALLOW_ALL_ORIGINS.
_cors_origins = [o.strip() for o in config('CORS_ALLOWED_ORIGINS', default='').split(',') if o.strip()]
if _cors_origins:
    CORS_ALLOWED_ORIGINS = _cors_origins
else:
    CORS_ALLOW_ALL_ORIGINS = True

# --- Channels (WebSocket temps réel) ---
ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(config('REDIS_HOST', default='localhost'), 6379)],
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Abidjan'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Photos des plats du menu (§5.6), uploadées via /admin/ ou l'API.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
