# Generated by Django 5.0.14 on 2026-07-07 14:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=80)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie de menu',
                'verbose_name_plural': 'Catégories de menu',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=100)),
                ('type_modifier', models.CharField(choices=[('allergie', 'Allergie'), ('preference', 'Préférence'), ('supplement', 'Supplément')], default='preference', max_length=20)),
                ('niveau_alerte_critique', models.BooleanField(default=False, help_text='Affichage renforcé sur le ticket (ex: allergie sévère)')),
                ('prix_supplement', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=20)),
                ('qr_code_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Token encodé dans le QR code imprimé, sert d'URL d'accès client", unique=True)),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupee', 'Occupée'), ('appel_serveur', 'Appel serveur actif')], default='libre', max_length=20)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=80)),
                ('is_expo', models.BooleanField(default=False, help_text='Écran de contrôle final avant envoi en salle (cf. §5.1)')),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_etablissement', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('logo_url', models.URLField(blank=True)),
                ('couleur_primaire', models.CharField(default='#1B2431', help_text='Code hexadécimal, ex: #1B2431', max_length=7)),
                ('couleur_secondaire', models.CharField(default='#C9A24B', max_length=7)),
                ('devise', models.CharField(choices=[('XOF', 'Franc CFA (XOF)'), ('EUR', 'Euro'), ('USD', 'Dollar US')], default='XOF', max_length=3)),
                ('langue_defaut', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2)),
                ('seuil_orange_minutes', models.PositiveIntegerField(default=10)),
                ('seuil_rouge_minutes', models.PositiveIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom_etablissement'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Manager'), ('cuisinier', 'Cuisinier'), ('serveur', 'Serveur')], default='serveur', max_length=20)),
                ('pin_code', models.CharField(blank=True, help_text='Code PIN haché (jamais stocké en clair) pour connexion rapide écran tactile', max_length=128)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('station_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='kds_core.station')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='kds_core.tenant')),
            ],
            options={
                'ordering': ['tenant', 'role', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=120)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temps_preparation_estime_min', models.PositiveIntegerField(default=10)),
                ('image_url', models.URLField(blank=True)),
                ('photo_dressage_url', models.URLField(blank=True, help_text='Photo de dressage pour la fiche technique cuisine')),
                ('fiche_technique', models.TextField(blank=True, help_text='Recette / instructions de préparation')),
                ('allergenes', models.JSONField(blank=True, default=list, help_text="Liste de libellés d'allergènes")),
                ('regimes', models.JSONField(blank=True, default=list, help_text="Ex: ['vegetarien', 'sans_porc', 'halal']")),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('rupture', "Rupture (86'd)")], default='disponible', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plats', to='kds_core.menucategory')),
                ('modifiers', models.ManyToManyField(blank=True, related_name='plats', to='kds_core.modifier')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plats', to='kds_core.station')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='kds_core.tenant')),
            ],
            options={
                'ordering': ['categorie__ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('salle', 'Prise en salle'), ('qr_code', 'QR Code client'), ('click_collect', 'Click & Collect'), ('yango', 'Yango Food'), ('glovo', 'Glovo')], default='salle', max_length=20)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_preparation', 'En préparation'), ('prete', 'Prête'), ('servie', 'Servie'), ('annulee', 'Annulée')], default='nouvelle', max_length=20)),
                ('is_rush', models.BooleanField(default=False, help_text='Priorité/urgence marquée manuellement')),
                ('reference_externe', models.CharField(blank=True, help_text='Identifiant côté POS ou plateforme tierce (Yango, Glovo...)', max_length=100)),
                ('serveur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_prises', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='kds_core.restauranttable')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='kds_core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('pret', 'Prêt'), ('servi', 'Servi')], default='en_attente', max_length=20)),
                ('is_held', models.BooleanField(default=False, help_text='Fire/Hold — envoi volontairement retenu (cf. §5.1)')),
                ('is_rush', models.BooleanField(default=False)),
                ('heure_envoi_poste', models.DateTimeField(blank=True, null=True)),
                ('heure_debut_preparation', models.DateTimeField(blank=True, null=True)),
                ('heure_pret', models.DateTimeField(blank=True, null=True)),
                ('heure_servi', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='kds_core.order')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='kds_core.station')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='kds_core.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='menucategory',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='kds_core.station'),
        ),
        migrations.AddField(
            model_name='station',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='kds_core.tenant'),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='kds_core.tenant'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('commentaire_libre', models.CharField(blank=True, max_length=255)),
                ('statut_ligne', models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('pret', 'Prêt'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('motif_annulation', models.CharField(blank=True, max_length=255)),
                ('modificateurs', models.ManyToManyField(blank=True, related_name='lignes_commande', to='kds_core.modifier')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='kds_core.menuitem')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='kds_core.orderticket')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='kds_core.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='modifier',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='kds_core.tenant'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='kds_core.tenant'),
        ),
        migrations.CreateModel(
            name='TicketStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ancien_statut', models.CharField(max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='kds_core.tenant')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_statut', to='kds_core.orderticket')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(fields=('tenant', 'nom'), name='unique_station_par_tenant'),
        ),
        migrations.AddConstraint(
            model_name='restauranttable',
            constraint=models.UniqueConstraint(fields=('tenant', 'numero'), name='unique_table_par_tenant'),
        ),
        migrations.AddIndex(
            model_name='orderticket',
            index=models.Index(fields=['tenant', 'station', 'statut'], name='kds_core_or_tenant__d6dbfc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'statut'], name='kds_core_or_tenant__000930_idx'),
        ),
    ]
