# Generated by Django 5.0.14 on 2026-07-08 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='Ex: « Caisse principale », nom du logiciel POS', max_length=100)),
                ('secret_hash', models.CharField(editable=False, max_length=128)),
                ('webhook_url', models.URLField(blank=True, help_text='Appelé en POST par le KDS quand une commande passe prête/servie')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='kds_core.tenant')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
