# Generated by Django 5.0.14 on 2026-07-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds_core', '0002_posintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='heure_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('carte', 'Carte'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='statut_paiement',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
