# Generated by Django 5.0.14 on 2026-07-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds_core', '0003_order_heure_paiement_order_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderticket',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('pret', 'Prêt'), ('servi', 'Servi'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
    ]
