# Generated by Django 5.0.14 on 2026-07-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds_core', '0004_alter_orderticket_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='statut_ligne',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('pret', 'Prêt'), ('servi', 'Servi'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
    ]
