# Generated by Django 5.0.14 on 2026-07-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds_core', '0005_alter_orderitem_statut_ligne'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text="Clé générée côté client QR (§5.5, file d'attente hors-ligne) : évite de créer un doublon si une commande mise en file IndexedDB est réémise après une coupure réseau dont on ne sait pas si elle a atteint le serveur avant de couper.", max_length=64),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'table', 'idempotency_key'], name='kds_core_or_tenant__16ff91_idx'),
        ),
    ]
