# Generated by Django 5.0.14 on 2026-07-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds_core', '0006_order_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='montant_recu',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant remis par le client (espèces) — sert à calculer la monnaie à rendre sur le reçu de caisse. Sans objet pour carte/mobile money (le montant reçu vaut alors le total, aucune monnaie à rendre).', max_digits=10, null=True),
        ),
    ]
