# Generated by Django 5.0.14 on 2026-07-13 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds_core', '0007_order_montant_recu'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='caissier',
            field=models.ForeignKey(blank=True, help_text="Manager/admin qui a traité l'encaissement — renseigné automatiquement par OrderViewSet.encaisser.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_encaissees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='numero_ticket',
            field=models.PositiveIntegerField(blank=True, help_text="Numéro séquentiel du reçu de caisse (par tenant), attribué à l'encaissement — affiché formaté 'TC-000056' sur le reçu imprimé. Absent tant que la commande n'est pas payée.", null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='telephone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
