# Generated by Django 5.0.14 on 2026-07-14 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds_core', '0009_remove_menuitem_image_url_remove_tenant_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='servi_par',
            field=models.ForeignKey(blank=True, help_text="Qui a confirmé ce plat servi — écran Service dédié ou bouton 'Marquer servi' cuisine, peu importe le chemin (§5.1, traçabilité de service demandée après coup).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_servies', to=settings.AUTH_USER_MODEL),
        ),
    ]
