# Generated by Django 5.0.14 on 2026-07-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds_core', '0010_orderitem_servi_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('especes', 'Espèces'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('momo', 'Momo'), ('carte', 'Carte'), ('autre', 'Autre')], max_length=20),
        ),
    ]
