# Generated by Django 5.0.14 on 2026-07-15 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds_core', '0011_alter_order_mode_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatLicenceLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('retard', 'Retard — avertissement'), ('retard_prolonge', 'Retard prolongé — rapports désactivés'), ('suspendu', 'Suspendu — accès bloqué')], default='actif', max_length=20)),
                ('date_prochaine_echeance', models.DateField(blank=True, null=True)),
                ('dernier_pointage_reussi', models.DateTimeField(blank=True, null=True)),
                ('derniere_tentative', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenceClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifiant', models.SlugField(help_text="Identifiant stable de l'installation (ex: slug du restaurant).", max_length=100, unique=True)),
                ('nom_client', models.CharField(max_length=150)),
                ('cle_api', models.CharField(editable=False, help_text="Secret partagé avec l'installation cliente pour authentifier ses pointages.", max_length=64, unique=True)),
                ('date_prochaine_echeance', models.DateField(help_text="Date jusqu'à laquelle l'abonnement est payé.")),
                ('dernier_pointage', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nom_client'],
            },
        ),
    ]
