# Generated by Django 5.0.14 on 2026-07-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds_core', '0012_etatlicencelocal_licenceclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('salle', 'Prise en salle'), ('qr_code', 'QR Code client'), ('click_collect', 'Click & Collect'), ('yango', 'Yango Food'), ('glovo', 'Glovo'), ('comptoir', 'Vente comptoir')], default='salle', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Manager'), ('cuisinier', 'Cuisinier'), ('serveur', 'Serveur'), ('caissier', 'Caissière')], default='serveur', max_length=20),
        ),
    ]
