# Generated by Django 5.0.14 on 2026-07-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds_core', '0013_alter_order_source_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='url_publique',
            field=models.URLField(blank=True, help_text="Adresse utilisée pour générer les QR codes clients (ex: http://192.168.1.6 sur une installation locale). Laisser vide pour retomber sur l'adresse du navigateur ayant généré le QR — fragile si générée depuis un appareil qui n'a pas la même adresse que celle utilisée par les clients (ex: le kiosque lui-même, qui charge souvent http://localhost/ plutôt que l'IP réseau de la machine)."),
        ),
    ]
