# Generated by Django 5.0.14 on 2026-07-17 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds_core', '0014_tenant_url_publique'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='annule_par',
            field=models.ForeignKey(blank=True, help_text="Manager/admin qui a validé l'annulation — renseigné automatiquement par OrderViewSet.cancel.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_annulees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='heure_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='motif_annulation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
