# Generated by Django 5.0.14 on 2026-07-17 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds_core', '0015_order_annule_par_order_heure_annulation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=80)),
                ('obligatoire', models.BooleanField(default=False)),
                ('selection_multiple', models.BooleanField(default=False)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='kds_core.tenant')),
            ],
            options={
                'verbose_name': 'Catégorie de modificateur',
                'verbose_name_plural': 'Catégories de modificateur',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='modifier',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modificateurs', to='kds_core.modifiercategory'),
        ),
    ]
