# Generated by Django 5.0.14 on 2026-07-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds_core', '0016_modifiercategory_modifier_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderticket',
            name='en_dernier',
            field=models.BooleanField(default=False),
        ),
    ]
