# Generated by Django 5.0.14 on 2026-07-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds_core', '0017_orderticket_en_dernier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Manager'), ('cuisinier', 'Cuisinier'), ('barman', 'Barman'), ('serveur', 'Serveur'), ('caissier', 'Caissière')], default='serveur', max_length=20),
        ),
    ]
