# Generated by Django 5.0.14 on 2026-07-18 01:03

from django.db import migrations, models


def _desamorcer_doublons_existants(apps, schema_editor):
    """
    Défensif, avant d'ajouter la contrainte unique ci-dessous : si une
    installation (VPS, VM cliente) a déjà accumulé des commandes en
    doublon à cause de la course corrigée aujourd'hui (deux requêtes
    concurrentes avec la même `idempotency_key`), `AddConstraint`
    échouerait sur des données déjà en violation. Ne supprime jamais une
    commande réelle — vide juste la clé sur les doublons les plus
    récents (garde le plus ancien), qui reste sinon la seule commande
    "propriétaire" légitime de cette clé.
    """
    Order = apps.get_model('kds_core', 'Order')
    doublons = (
        Order.objects.exclude(idempotency_key='')
        .values('tenant_id', 'table_id', 'idempotency_key')
        .annotate(n=models.Count('id'))
        .filter(n__gt=1)
    )
    for d in doublons:
        ids_a_vider = list(
            Order.objects.filter(
                tenant_id=d['tenant_id'], table_id=d['table_id'], idempotency_key=d['idempotency_key'],
            ).order_by('created_at').values_list('id', flat=True)[1:]
        )
        Order.objects.filter(id__in=ids_a_vider).update(idempotency_key='')


class Migration(migrations.Migration):

    dependencies = [
        ('kds_core', '0018_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(_desamorcer_doublons_existants, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='order',
            name='kds_core_or_tenant__16ff91_idx',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('tenant', 'table', 'idempotency_key'), name='unique_idempotency_key_par_table'),
        ),
    ]
